### ISSUE TITLE
Poorly Documented

### ISSUE THREAD

**Issue by ghost** [jeske/SoundLevelMonitor#1]
Hi I was reviewing your project because I'm constructing an LED blinker with an ESPP8266 board and I am new to this audio library. I want to say one thing. It was very BADLY documented. I haven't got a clue where the data comes from in the library and how your quite slow UI control get's it from. All it seems to have is shitty UI code that does some calculations. No data input anywhere. At least not at the moment. Please consider re-documenting the source because it's really hard to read.

**Comment by jeske** [comment]
I wrote this project for myself.. and as far as I know, I'm the only one who has ever used it. 

I put the code on github and made it free. If you are not happy with it, you are entitled to a full refund.
